name: scientific-calculator
region: nyc

services:
  - name: web
    github:
      repo: bikram20/scientific-calculator
      branch: master
      deploy_on_push: true
    source_dir: /
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

